import * as React from 'react';
import { SmallTile, PdfButton } from "../Components";
export class ResumePage extends React.Component {
    constructor(props) {
        super(props);
    }
    render() {
        return (React.createElement("div", { className: "resume secondary-content-width flex-column center-horizontal" },
            React.createElement("h1", { className: "resume-print-title" }, "Oliver McMillan"),
            React.createElement("div", { className: "resume-summary flex-row" },
                React.createElement("p", null, "Experienced Software Engineer with a demonstrated history of working in the telecommunications industry. Skilled in C#, SQL, web architecture, and front-end web development. Organized and dedicated engineering professional with a BCS qualification."),
                React.createElement(PdfButton, null)),
            React.createElement("div", { className: "resume-vertical-divider" }),
            React.createElement("div", { className: "flex-row" },
                React.createElement("div", { className: "resume-left-column" },
                    React.createElement("h2", null, "Work Experience"),
                    React.createElement("h3", null, "Metricell"),
                    React.createElement("h4", null, "2017 - Present"),
                    React.createElement("ul", null,
                        React.createElement("li", null, "Maintained and enhanced systems to automatically aggregate and visualize geospatial data."),
                        React.createElement("li", null, "Designed and implemented secure login systems, user permission and profile management features, and automated download pages."),
                        React.createElement("li", null, "Used APIs to implement live feed data displays and create support tickets."),
                        React.createElement("li", null, "Maintained and supported large databases. 3000+ objects, 50,000,000,000+ records."),
                        React.createElement("li", null, "Managed regular live web deployments.")),
                    React.createElement("h3", null, "UNUM"),
                    React.createElement("h4", null, "2015 - 2017 Part Time"),
                    React.createElement("ul", null,
                        React.createElement("li", null, "Auditing IT equipment."),
                        React.createElement("li", null, "Setting up and distributing new equiment."),
                        React.createElement("li", null, "Performing hardware and sofware maintenance on existing IT equipment.")),
                    React.createElement("h2", null, "Skills"),
                    React.createElement("div", { className: "flex-row flex-wrap" },
                        React.createElement(SmallTile, { text: "React" }),
                        React.createElement(SmallTile, { text: "HTML" }),
                        React.createElement(SmallTile, { text: "JavaScript" }),
                        React.createElement(SmallTile, { text: "TypeScript" }),
                        React.createElement(SmallTile, { text: "SASS" }),
                        React.createElement(SmallTile, { text: "CSS" }),
                        React.createElement(SmallTile, { text: "WebPack" }),
                        React.createElement(SmallTile, { text: "C#" }),
                        React.createElement(SmallTile, { text: ".Net FrameWork" }),
                        React.createElement(SmallTile, { text: ".Net Core" }),
                        React.createElement(SmallTile, { text: "MVC Architecture" }),
                        React.createElement(SmallTile, { text: "Node JS" }),
                        React.createElement(SmallTile, { text: "WPF" }),
                        React.createElement(SmallTile, { text: "XAML" }),
                        React.createElement(SmallTile, { text: "SQL" }),
                        React.createElement(SmallTile, { text: "SQL Server Agent" }),
                        React.createElement(SmallTile, { text: "Q-GIS" })),
                    React.createElement("h2", null, "Qualifications"),
                    React.createElement("h3", null, "BCS Software Development Technician Level 3 with Merit"),
                    React.createElement("p", null, "I started my work at Metricell as an apprentice, to this end I took courses provided by QA and earned a Level 3 BCS Software Development Technician qualification with a merit."),
                    React.createElement("h3", null, "Duke of Edinburgh Awards, Bronze & Silver"),
                    React.createElement("h2", null, "Education"),
                    React.createElement("h3", null, "Reigate College"),
                    "AS Levels",
                    React.createElement("ul", null,
                        React.createElement("li", null, "Computer Science"),
                        React.createElement("li", null, "Physics"),
                        React.createElement("li", null, "Maths")),
                    React.createElement("h3", null, "Aschcombe School"),
                    "GSCEs",
                    React.createElement("ul", null,
                        React.createElement("li", null, "Maths"),
                        React.createElement("li", null, "Double Science"),
                        React.createElement("li", null, "Computer Science"))),
                React.createElement("div", { className: "resume-horizontal-divider" }),
                React.createElement("div", { className: "resume-right-column" },
                    React.createElement("h3", null, "Info"),
                    React.createElement("h4", null, "Email"),
                    React.createElement("a", { href: `mailto:${window.variables.emailAddress}` },
                        React.createElement("span", null, `${window.variables.emailAddress}`)),
                    React.createElement("h4", null, "LinkedIn"),
                    React.createElement("a", { href: "https://www.linkedin.com/in/oliver-mcmillan/", target: "_blank" },
                        React.createElement("span", null, "Oliver McMillan"))))));
    }
}
//# sourceMappingURL=ResumePage.js.map